package indi.dmzz_yyhyy.lightnovelreader.ui.book.reader

import android.net.Uri
import androidx.compose.runtime.getValue
import androidx.compose.ui.graphics.Color
import indi.dmzz_yyhyy.lightnovelreader.data.setting.AbstractSettingState
import indi.dmzz_yyhyy.lightnovelreader.data.userdata.UserDataRepository
import indi.dmzz_yyhyy.lightnovelreader.ui.home.settings.data.MenuOptions
import io.nightfish.lightnovelreader.api.userdata.UserDataPath
import kotlinx.coroutines.CoroutineScope

@Suppress("MemberVisibilityCanBePrivate")
class SettingState(
    userDataRepository: UserDataRepository,
    coroutineScope: CoroutineScope
) : AbstractSettingState(coroutineScope) {
    val fontSizeUserData = userDataRepository.floatUserData(UserDataPath.Reader.FontSize.path)
    val fontLineHeightUserData = userDataRepository.floatUserData(UserDataPath.Reader.FontLineHeight.path)
    val fontWeighUserData = userDataRepository.floatUserData(UserDataPath.Reader.FontWeigh.path)
    val keepScreenOnUserData = userDataRepository.booleanUserData(UserDataPath.Reader.KeepScreenOn.path)
    val enableHideStatusBarUserData = userDataRepository.booleanUserData(UserDataPath.Reader.EnableHideStatusBar.path)
    val enableBackgroundImageUserData = userDataRepository.booleanUserData(UserDataPath.Reader.EnableBackgroundImage.path)
    val backgroundImageDisplayModeUserData = userDataRepository.stringUserData(UserDataPath.Reader.BackgroundImageDisplayMode.path)
    val isUsingFlipPageUserData = userDataRepository.booleanUserData(UserDataPath.Reader.IsUsingFlipPage.path)
    val isUsingClickFlipPageUserData = userDataRepository.booleanUserData(UserDataPath.Reader.IsUsingClickFlipPage.path)
    val isUsingContinuousScrollingUserData = userDataRepository.booleanUserData(UserDataPath.Reader.IsUsingContinuousScrolling.path)
    val isUsingVolumeKeyFlipUserData = userDataRepository.booleanUserData(UserDataPath.Reader.IsUsingVolumeKeyFlip.path)
    val volumeKeyContinuousFlipIntervalUserData = userDataRepository.floatUserData(UserDataPath.Reader.VolumeKeyContinuousFlipInterval.path)
    val flipAnimeUserData = userDataRepository.stringUserData(UserDataPath.Reader.FlipAnime.path)
    val fastChapterChangeUserData = userDataRepository.booleanUserData(UserDataPath.Reader.FastChapterChange.path)
    val batteryIndicatorDisplayModeUserData = userDataRepository.stringUserData(UserDataPath.Reader.BatteryIndicatorDisplayMode.path)
    val enableTimeIndicatorUserData = userDataRepository.booleanUserData(UserDataPath.Reader.EnableTimeIndicator.path)
    val enableChapterTitleIndicatorUserData = userDataRepository.booleanUserData(UserDataPath.Reader.EnableChapterTitleIndicator.path)
    val enableReadingChapterProgressIndicatorUserData = userDataRepository.booleanUserData(UserDataPath.Reader.EnableReadingChapterProgressIndicator.path)
    val autoPaddingUserData = userDataRepository.booleanUserData(UserDataPath.Reader.AutoPadding.path)
    val topPaddingUserData = userDataRepository.floatUserData(UserDataPath.Reader.TopPadding.path)
    val bottomPaddingUserData = userDataRepository.floatUserData(UserDataPath.Reader.BottomPadding.path)
    val leftPaddingUserData = userDataRepository.floatUserData(UserDataPath.Reader.LeftPadding.path)
    val rightPaddingUserData = userDataRepository.floatUserData(UserDataPath.Reader.RightPadding.path)
    val textColorUserData = userDataRepository.colorUserData(UserDataPath.Reader.TextColor.path)
    val textDarkColorUserData = userDataRepository.colorUserData(UserDataPath.Reader.TextDarkColor.path)
    val fontFamilyUriUserData = userDataRepository.uriUserData(UserDataPath.Reader.FontFamilyUri.path)
    val backgroundColorUserData = userDataRepository.colorUserData(UserDataPath.Reader.BackgroundColor.path)
    val backgroundDarkColorUserData = userDataRepository.colorUserData(UserDataPath.Reader.BackgroundDarkColor.path)
    val backgroundImageUriUserData = userDataRepository.uriUserData(UserDataPath.Reader.BackgroundImageUri.path)
    val backgroundDarkImageUriUserData = userDataRepository.uriUserData(UserDataPath.Reader.BackgroundDarkImageUri.path)
    val darkModeKeyUserData = userDataRepository.stringUserData(UserDataPath.Settings.Display.DarkMode.path)
    val dynamicColorsKeyUserData = userDataRepository.booleanUserData(UserDataPath.Settings.Display.DynamicColors.path)
    val enableM3EUserData = userDataRepository.booleanUserData(UserDataPath.Settings.Display.EnableM3E.path)
    val enableCostumeThemeSchemeUserData = userDataRepository.booleanUserData(UserDataPath.Settings.Display.EnableCostumeThemeScheme.path)
    val lightThemeNameUserData = userDataRepository.stringUserData(UserDataPath.Settings.Display.LightThemeName.path)
    val darkThemeNameUserData = userDataRepository.stringUserData(UserDataPath.Settings.Display.DarkThemeName.path)
    val backBlockModeUserData = userDataRepository.stringUserData(UserDataPath.Reader.BackBlockMode.path)
    // costume theme scheme
    val costumeThemeSchemePrimaryUserData = userDataRepository.colorUserData(UserDataPath.Settings.Display.CostumeThemeSchemePrimary.path)
    val costumeThemeSchemeOnPrimaryUserData = userDataRepository.colorUserData(UserDataPath.Settings.Display.CostumeThemeSchemeOnPrimary.path)
    val costumeThemeSchemePrimaryContainerUserData = userDataRepository.colorUserData(UserDataPath.Settings.Display.CostumeThemeSchemePrimaryContainer.path)
    val costumeThemeSchemeOnPrimaryContainerUserData = userDataRepository.colorUserData(UserDataPath.Settings.Display.CostumeThemeSchemeOnPrimaryContainer.path)
    val costumeThemeSchemeSecondaryUserData = userDataRepository.colorUserData(UserDataPath.Settings.Display.CostumeThemeSchemeSecondary.path)
    val costumeThemeSchemeOnSecondaryUserData = userDataRepository.colorUserData(UserDataPath.Settings.Display.CostumeThemeSchemeOnSecondary.path)
    val costumeThemeSchemeSecondaryContainerUserData = userDataRepository.colorUserData(UserDataPath.Settings.Display.CostumeThemeSchemeSecondaryContainer.path)
    val costumeThemeSchemeOnSecondaryContainerUserData = userDataRepository.colorUserData(UserDataPath.Settings.Display.CostumeThemeSchemeOnSecondaryContainer.path)
    val costumeThemeSchemeTertiaryUserData = userDataRepository.colorUserData(UserDataPath.Settings.Display.CostumeThemeSchemeTertiary.path)
    val costumeThemeSchemeOnTertiaryUserData = userDataRepository.colorUserData(UserDataPath.Settings.Display.CostumeThemeSchemeOnTertiary.path)
    val costumeThemeSchemeTertiaryContainerUserData = userDataRepository.colorUserData(UserDataPath.Settings.Display.CostumeThemeSchemeTertiaryContainer.path)
    val costumeThemeSchemeOnTertiaryContainerUserData = userDataRepository.colorUserData(UserDataPath.Settings.Display.CostumeThemeSchemeOnTertiaryContainer.path)
    val costumeThemeSchemeBackgroundUserData = userDataRepository.colorUserData(UserDataPath.Settings.Display.CostumeThemeSchemeBackground.path)
    val costumeThemeSchemeOnBackgroundUserData = userDataRepository.colorUserData(UserDataPath.Settings.Display.CostumeThemeSchemeOnBackground.path)
    val costumeThemeSchemeSurfaceUserData = userDataRepository.colorUserData(UserDataPath.Settings.Display.CostumeThemeSchemeSurface.path)
    val costumeThemeSchemeOnSurfaceUserData = userDataRepository.colorUserData(UserDataPath.Settings.Display.CostumeThemeSchemeOnSurface.path)
    val costumeThemeSchemeErrorUserData = userDataRepository.colorUserData(UserDataPath.Settings.Display.CostumeThemeSchemeError.path)
    val costumeThemeSchemeOnErrorUserData = userDataRepository.colorUserData(UserDataPath.Settings.Display.CostumeThemeSchemeOnError.path)

    val fontSize by fontSizeUserData.safeAsState(15f)
    val fontLineHeight by fontLineHeightUserData.safeAsState(7f)
    val fontWeigh by fontWeighUserData.safeAsState(500f)
    val keepScreenOn by keepScreenOnUserData.safeAsState(false)
    val enableHideStatusBar by enableHideStatusBarUserData.safeAsState(true)
    val enableBackgroundImage by enableBackgroundImageUserData.safeAsState(false)
    val backgroundImageDisplayMode by backgroundImageDisplayModeUserData.safeAsState("fixed")
    val isUsingFlipPage by isUsingFlipPageUserData.safeAsState(false)
    val isUsingClickFlipPage by isUsingClickFlipPageUserData.safeAsState(false)
    val isUsingContinuousScrolling by isUsingContinuousScrollingUserData.safeAsState(true)
    val isUsingVolumeKeyFlip by isUsingVolumeKeyFlipUserData.safeAsState(false)
    val volumeKeyContinuousFlipInterval by volumeKeyContinuousFlipIntervalUserData.safeAsState(-1f)
    val flipAnime by flipAnimeUserData.safeAsState(MenuOptions.FlipAnimationOptions.ScrollWithoutShadow)
    val fastChapterChange by fastChapterChangeUserData.safeAsState(false)
    val batteryIndicatorDisplayMode by batteryIndicatorDisplayModeUserData.safeAsState("classic")
    val enableTimeIndicator by enableTimeIndicatorUserData.safeAsState(true)
    val enableChapterTitleIndicator by enableChapterTitleIndicatorUserData.safeAsState(true)
    val enableReadingChapterProgressIndicator by enableReadingChapterProgressIndicatorUserData.safeAsState(true)
    val autoPadding by autoPaddingUserData.safeAsState(true)
    val topPadding by topPaddingUserData.safeAsState(12f)
    val bottomPadding by bottomPaddingUserData.safeAsState(12f)
    val leftPadding by leftPaddingUserData.safeAsState(16f)
    val rightPadding by rightPaddingUserData.safeAsState(16f)
    val textColor by textColorUserData.safeAsState(Color.Unspecified)
    val textDarkColor by textDarkColorUserData.safeAsState(Color.Unspecified)
    val fontFamilyUri by fontFamilyUriUserData.safeAsState(Uri.EMPTY)
    val backgroundColor by backgroundColorUserData.safeAsState(Color.Unspecified)
    val backgroundDarkColor by backgroundDarkColorUserData.safeAsState(Color.Unspecified)
    val backgroundImageUri by backgroundImageUriUserData.safeAsState(Uri.EMPTY)
    val backgroundDarkImageUri by backgroundDarkImageUriUserData.safeAsState(Uri.EMPTY)
    val darkModeKey by darkModeKeyUserData.safeAsState("FollowSystem")
    val dynamicColorsKey by dynamicColorsKeyUserData.safeAsState(false)
    val enableM3E by enableM3EUserData.safeAsState(false)
    val enableCostumeThemeScheme by enableCostumeThemeSchemeUserData.safeAsState(false)
    val lightThemeName by lightThemeNameUserData.safeAsState("light_default")
    val darkThemeName by darkThemeNameUserData.safeAsState("dark_default")
    val backBlockMode by backBlockModeUserData.safeAsState("none")
}
